### ISSUE TITLE
[2.0.0] Todo list

### ISSUE THREAD

**Issue by OddOneOut** [OddOneOut/bwp-recaptcha#2]
**Todo list for 2.0.0 (finalized)**

* [x] update documentaion (use RST)
* [x] Add support for custom login/register url #16 
* [x] Add support for recaptcha v2 (No Captcha Recaptcha) #6 
* [x] Add support for Contact Form 7 version 4.x #3 
* [x] Add https option (recaptcha v1 only) #9 
* [x] Add support for multiple re-captcha instances on a page (recaptcha v2 only) #10 
* [x] Fix session creation issue #11

**Comment by dregad** [comment]
Greetings. Do you have any ETA on implementing support for recaptcha v2 ?

**Comment by kminh** [comment]
@dregad will follow this announcement closely: http://betterwp.net/better-wordpress-plugins-updates-2015/

**Comment by Sophist-UK** [comment]
Looking forward to the next version with support for reCaptcha v2 - I received a google reminder to switch this morning.
